global:
  #defines how often to check for new metric values.
  scrape_interval: 30s
  #rometheus will cancel the scrape if the below limit exceeds
  scrape_timeout: 10s

#Intimate Prometheus with the  application
scrape_configs:
  - job_name: services
    metrics_path: /metrics
    #end-points
    static_configs:
      - targets:
          - 'csvserver:9300'
